server:
  port: 8093
  servlet:
    context-path: /
spring:
  datasource:
    #引入druid数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.88.240:3306/jsgdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.jsg.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level: 
    com.jt.mapper: debug
dubbo:
  scan:
    basePackages: com.jt
  application:
    name: provider-user
  registry:
    address: zookeeper://192.168.88.129:2181?backup=192.168.88.129:2182,192.168.88.129:2183
  protocol: #协议
    name: dubbo #使用的是Dubbo默认的协议
    port: 20880  #端口号唯一
